import 'package:campuscare/models/tiket_model.dart';

TiketModel makeTicket({
  String? id,
  String idTiket = 'TKT-2026-001',
  String idUser = '6672a1b4f3c3c3c3c3c3c3c1',
  String emailUser = 'mahasiswa@polban.ac.id',
  String judulSingkat = 'Keran toilet rusak',
  String deskripsiTiket = 'Keran toilet lantai satu tidak bisa ditutup rapat.',
  String? deskripsiLokasi = 'Dekat toilet pria',
  String kategoriUtama = 'Sarpras',
  String kategoriJenis = 'Kerusakan Fasilitas',
  String gedung = 'Gedung JTK',
  int lantai = 1,
  String ruangan = 'Toilet',
  List<String> buktiVisual = const ['https://example.com/foto.jpg'],
  String status = 'Menunggu Verifikasi',
  String? tingkatUrgensi,
  DateTime? tanggalPembuatan,
  DateTime? tanggalPengajuan,
  DateTime? tanggalVerifikasi,
  DateTime? tanggalApproval,
  DateTime? tanggalRejection,
  DateTime? tanggalExport,
  String? alasanRejection,
  String? catatanPJ,
  String? idPenanggungJawab,
  int jumlahVote = 0,
  List<CommentModel> comments = const [],
  DateTime? createdAt,
  DateTime? updatedAt,
  DateTime? deletedAt,
}) {
  final now = DateTime(2026, 6, 2, 9, 0);

  return TiketModel(
    id: id,
    idTiket: idTiket,
    idUser: idUser,
    emailUser: emailUser,
    judulSingkat: judulSingkat,
    deskripsiTiket: deskripsiTiket,
    deskripsiLokasi: deskripsiLokasi,
    kategori: KategoriModel(utama: kategoriUtama, jenis: kategoriJenis),
    lokasi: LokasiModel(gedung: gedung, lantai: lantai, ruangan: ruangan),
    buktiVisual: buktiVisual,
    status: status,
    tingkatUrgensi: tingkatUrgensi,
    tanggalPembuatan: tanggalPembuatan ?? now,
    tanggalPengajuan: tanggalPengajuan ?? now,
    tanggalVerifikasi: tanggalVerifikasi,
    tanggalApproval: tanggalApproval,
    tanggalRejection: tanggalRejection,
    tanggalExport: tanggalExport,
    alasanRejection: alasanRejection,
    catatanPJ: catatanPJ,
    idPenanggungJawab: idPenanggungJawab,
    jumlahVote: jumlahVote,
    comments: comments,
    createdAt: createdAt ?? now,
    updatedAt: updatedAt ?? now,
    deletedAt: deletedAt,
  );
}
